# Generated by Django 5.0.3 on 2024-03-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('postcode', models.CharField(max_length=50, verbose_name='postcode')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['pk', 'title', 'postcode'],
            },
        ),
    ]
